### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by apetenchea**
While reading the documentation, I stumbled across the following typos:
- `xtheadsync/sync_is.adoc`: incomplete synopsis
- `xtheadmemidx/lbuia.adoc`: _rs_ register should be _rd_ in the example
- `xtheadmemidx/ldib.adoc`: mnemonic shows `lwib` instead of `ldib`

### CODE REVIEW

**Review by cmuellner — APPROVED** [review]
LGTM

Thanks!

**Comment by apetenchea** [comment]
Thanks @cmuellner for the review!
I figured this is already the best place for suggesting another small fix on the `ldib` mnemonic (https://github.com/T-head-Semi/thead-extension-spec/pull/53/commits/5db5d28251a90760a9856110d222bcbde1f2f532)

**Review by cmuellner — APPROVED** [review]
LGTM

**Comment by Cooper-Qu** [comment]
LGTM.
Thanks!

**Pull request merged**
